import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHandHoldingDollar,
  faLightbulb,
  faMedal,
  faFistRaised,
  faTv,
  faDroplet,
  faBrain,
  faArrowsToCircle,
  faHandHoldingHand
} from "@fortawesome/free-solid-svg-icons";

export const servicesData = [
    { 
        id: 0,
       icon: faFistRaised,
       title: "Woman Empowerment",
       img1:"https://imagizer.imageshack.com/v2/1024x768q70/923/Lxx0kV.jpg",
       img2:"https://imagizer.imageshack.com/v2/640x480q70/923/AuYBcb.png",
       img3:"https://imagizer.imageshack.com/v2/640x480q70/924/bxl7mm.jpg",
       description: "Empowering women leaders in Sidama through training, advocacy on national media, and scholarships for seven women. This initiative addresses gender disparities and promotes meaningful change by combining various supportive efforts.",
       fulldescription: "GSC=> empowering women leaders in the Sidama Regional State is truly commendable! By combining training sessions for women commissioners with advocacy efforts on national radio and television, as well as providing scholarships to seven deserving women, you're addressing gender disparities from multiple angles. Here's how each aspect of your initiative contributes to meaningful change:1. **Training for Women Commissioners:** The three-day training program offers a valuable opportunity for the 42 higher-level women commissioners to enhance their leadership skills, network with peers, and gain knowledge in critical areas such as communication, negotiation, and strategic planning. By investing in their professional development, and equipping them to navigate the challenges of leadership roles effectively.2. **Advocacy on National Media Platforms:** Broadcasting our advocacy efforts on national radio and television amplifies the visibility of women leaders and the importance of gender equality in leadership positions. By reaching a broader audience, we are not only inspiring other women to pursue leadership roles but also raising awareness about the value of diversity and inclusion in governance.",
       fulldescription2: "Advocacy on National Media Platforms:** Broadcasting our advocacy efforts on national radio and television amplifies the visibility of women leaders and the importance of gender equality in leadership positions. By reaching a broader audience, we are not only inspiring other women to pursue leadership roles but also raising awareness about the value of diversity and inclusion in governance",
     },
     {
        id:1,
       icon: faHandHoldingDollar,
       title: "Scholarships for Women",
       img1: "https://imagizer.imageshack.com/v2/1600x1200q70/924/Ug1pAF.jpg",
       description: "Providing seven women with scholarships to access education and leadership opportunities. By removing financial barriers, we enable these women to pursue higher education and contribute meaningfully to their communities.",
       fulldescription: "Providing scholarships to seven women further promotes access to education and leadership opportunities. By removing financial barriers, we're enabling these women to pursue higher education or skill development programs that can unlock their full potential and empower them to contribute meaningfully to their communities and society at large",
     },
     { 
       id:2,
       icon: faArrowsToCircle,
       title: "Comprehensive Impact",
      img1: "https://imagizer.imageshack.com/img922/1668/L0MWhM.jpg",
       description: "These initiatives create a synergistic effect, fostering a supportive ecosystem that promotes women's advancement. By investing in leadership at various levels, we're contributing to sustainable societal growth.",
       fulldescription: " **Comprehensive Impact:** Together, these initiatives create a synergistic effect that goes beyond individual empowerment. By investing in women's leadership at various levels, from government officials to aspiring students, we're fostering a supportive ecosystem that promotes women's advancement and contributes to sustainable societal growth and development.",
     },
     {
       id:3,
       icon: faLightbulb,
       title: "Role Modeling and Inspiration",
       img1: "https://imagizer.imageshack.com/img922/4749/kONsZu.jpg",
       img2: "https://imagizer.imageshack.com/img922/1120/YxyDGe.jpg",
       img3: "https://imagizer.imageshack.com/img924/1746/MQzMAA.jpg",
       description: "Our initiative serves as a powerful example of addressing gender disparities and promoting women's leadership. By showcasing success stories and providing support, we inspire others to take similar actions.",
       fulldescription: "**Role Modeling and Inspiration:** our initiative serves as a powerful example of proactive efforts to address gender disparities and promote women's leadership. By showcasing success stories and providing tangible support, we're inspiring others to take similar actions and challenging existing norms and stereotypes.In summary, our multifaceted approach to empowering women leaders in the Sidama Regional State demonstrates a deep commitment to fostering gender equality and creating opportunities for women to thrive. By investing in training, advocacy, and scholarships, we're laying the foundation for a more inclusive and prosperous society where women's voices are heard and valued.",
     },
     {
       id:4,
       icon: faMedal,
       title: "Recognizing the Champions behind the scenes",
       img1: "https://imagizer.imageshack.com/img924/1262/4VRvw2.jpg",
       img2: "https://imagizer.imageshack.com/img923/9103/WxkkLw.jpg",
       description: "Golden Stars College honors mothers who have supported their children through their academic journeys. Recognizing these unsung heroes highlights their important role and contribution to their children's success.",
       fulldescription: "Golden Stars College is taking a heartfelt initiative to recognize and appreciate the silent yet powerful forces behind the success of its graduates. In a heartfelt gesture, the college is honoring the mothers who have steadfastly supported their children through their academic journeys. These unsung heroes, often working tirelessly behind the scenes, are finally getting the recognition they truly deserve.Through a series of ceremonies and media campaigns, Golden Stars College is shedding light on the sacrifices and unwavering support provided by these remarkable mothers. By showcasing their stories of dedication and resilience, the college aims to inspire a greater sense of appreciation and respect for all mothers who selflessly devote themselves to their children's success.Join us as we celebrate these extraordinary women and acknowledge the pivotal role they play in shaping the future generation. Together, let's honor our heroes behind the scenes and ensure that their contributions are never overlooked or underestimated.",
     },
     { 
       id:5,
       icon: faTv,
       title: "Media Campaign",
       img1: "https://imagizer.imageshack.com/img922/2152/COYEFj.jpg",
       img2: "https://imagizer.imageshack.com/img924/4862/mdhz33.jpg",
       img3: "https://imagizer.imageshack.com/img924/3236/KPEWzi.jpg",
       img4: "https://imagizer.imageshack.com/img924/1928/TTo4pD.jpg",
       description: "Utilizing media to spread awareness about the sacrifices of mothers. Through press releases, social media, and video documentaries, we highlight the supportive role of these 12 mothers.",
       fulldescription: "   - Utilize various media channels to spread awareness about the sacrifices of mothers and the importance of honoring them. Create press releases, social media posts, and video documentaries highlighting the stories of these 12 mothers and their supportive role By implementing this program, we can created lasting awareness about the invaluable role mothers play in the success of their children and inspire others to appreciate and honor them accordingly.",
     },
     {
       id:6,
       icon: faDroplet,
       title: "Blood Donation",
       img1: "https://imagizer.imageshack.com/img924/4470/ZWTXaV.jpg",
       img2: "https://imagizer.imageshack.com/img924/133/aXUAfv.jpg",
       description: "Blood donation saves lives every day. Donated blood helps individuals undergoing surgeries, cancer patients, and accident victims. This act of generosity embodies compassion and community support.",
       fulldescription: "Blood donation is a vital act of generosity that saves countless lives every day. When we donate blood, we're providing a lifeline to those in need, including individuals undergoing surgeries, cancer patients, accident victims, and many others. The blood we donate can be separated into its various components like red blood cells, platelets, and plasma, which can be used to treat different medical conditions.Overall, blood donation is a selfless act that embodies the spirit of compassion and community support.Golden Stars College spearheading initiatives to motivate students to engage in meaningful acts of altruism like blood donation. With over 100 students participating each year, the impact on the community's health and well-being cannot be overstated. By promoting responsibility and compassion among the youth, the college is not only nurturing future leaders but also fostering a culture of giving back to society. Keep up the excellent work, Golden Stars College! Our efforts are making a real difference in the lives of many.",
     },
     {
       id: 7,
       icon: faBrain,
       title: "Entrepreneurial Mindset",
       img1: "https://imagizer.imageshack.com/img924/4407/DtZrTZ.jpg",
       img2: "https://imagizer.imageshack.com/img923/3461/gChlap.jpg",
       description: "Encouraging graduates to adopt an entrepreneurial mindset by fostering creativity and resilience. Strategies include entrepreneurship education, business planning, and innovation workshops.",
       fulldescription: "Encouraging graduates to adopt an entrepreneurial mindset is about fostering creativity, resilience, and a proactive approach to problem-solving. Here are some strategies to help change their attitudes:1. **Education and Exposure**: Integrate entrepreneurship education into academic curricula. Offer courses or workshops that cover topics like business planning, innovation, and risk management. Additionally, provide opportunities for students to interact with successful entrepreneurs through guest lectures, networking events, or mentorship programs.",
     },
     {
       id:8,
       icon:   faHandHoldingHand,
       title: "Unity in Diversity",
       img1: "https://imagizer.imageshack.com/v2/1600x1200q70/923/zwPhQh.jpg",
       img2: "https://imagizer.imageshack.com/img923/6756/zwPhQh.jpg",
       img3: "https://imagizer.imageshack.com/img924/2699/woeHiQ.jpg",
       description: "Celebrating national and cultural events at Golden Stars College promotes equality and respect among students. These celebrations foster understanding, break down stereotypes, and create an inclusive environment.",
       fulldescription: "Golden Stars College! Celebrating national, cultural, and ceremonial events can be a powerful way to promote equality and respect among different ethnic groups of students. By participating in these celebrations, students have the opportunity to learn about different cultures, traditions, and histories, which fosters understanding and appreciation for diversity. It helps break down stereotypes and prejudices, promoting a more inclusive environment where everyone feels valued and respected regardless of their background. Through such events, students can actively engage in promoting a culture of inclusivity and respect within their school communities.",
     },

]